calog-project/calog-server

package-lock.json
package.json
src/app.module.ts

:package: Chore: ioredis 추가 패키지 설정 추가

---

src/common/type/CommonType.ts
src/main.ts
src/user/application/service/user.service.ts
src/user/application/user.controller.ts
src/user/domain/port/create-user.port.ts
src/user/domain/port/get-user.port.ts
src/user/domain/usecase/create-user.usecase.ts
src/user/domain/usecase/get-user.usecase.ts
src/user/infra/persistence/adapter/user-repository.adapter.ts
src/user/infra/persistence/entity/user.entity.ts
src/user/infra/user-persistence.module.ts

- user 도메인 getUser api 추가
- app 구동 전 설정 세팅 관련 코드 리팩토링 및 커스텀 타입 추가
- 오타 수정

✨Feat: user 도메인 getUser api 추가

---

.github/workflows/dev.yml

- github actions를 사용해 ssh 접속으로 ec2에 변경 사항 자동 배포

📦️ Chore: github actions CD 추가

---

src/auth/infra/in/http/adapter/auth.controller.ts
src/auth/infra/in/http/dto/auth.req.ts
src/common/config/app.config.ts
src/common/interceptor/set-token.interceptor.ts
src/main.ts

- oauth 인증 시 컨트롤러 리턴으로 되어있어 리다이렉트로 수정
- cors 설정 추가

🐛 Fix: oauth 인증 오류 수정, 리다이렉트 추가

---

.github/workflows/dev.yml

- 자동 배포 yml 파일 수정, 코드 푸시 이후 actions 실행

🐛 Fix: 자동 배포 yml 파일 수정

---

src/common/interceptor/response.interceptor.ts

🐛 Fix: 응답 인터셉터 오류 수정

---

src/user/application/service/user.service.ts
src/user/infra/in/http/adapter/user.controller.ts

🐛 Fix: 사용자 닉네임 중복확인 api 오류 수정

---

package-lock.json
package.json
src/common/interceptor/response.interceptor.ts
src/schedule/infra/out/persistence/adapter/schedule-repository.adapter.ts

- 잘못된 연산자로 인한 상태코드 관련 버그 수정
- 파일명 오타 수정
- TypeORM 네이밍 관련 패키지 추가

🐛 Fix: 상태코드 오류 수정

---

src/schedule/application/command/category.command-handler.ts
src/schedule/application/command/category.command.ts
src/schedule/application/query/category.query-handler.ts
src/schedule/application/query/category.query.ts
src/schedule/application/service/category.service.ts
src/schedule/domain/model/category.ts
src/schedule/domain/model/schedule.ts
src/schedule/domain/port/in/create-category.usecase.ts
src/schedule/domain/port/in/get-category.usecase.ts
src/schedule/domain/port/out/handle-category.port.ts
src/schedule/domain/port/out/load-category.port.ts
src/schedule/domain/port/out/load-schedule.port.ts
src/schedule/infra/in/http/adapter/category.controller.ts
src/schedule/infra/in/http/dto/category.req.ts
src/schedule/infra/in/http/dto/category.res.ts
src/schedule/infra/in/http/mapper/category.mapper.ts
src/schedule/infra/out/persistence/adapter/category-repository.adapter.ts
src/schedule/infra/out/persistence/entity/category.entity.ts
src/schedule/infra/out/persistence/entity/user-category-schedule.entity.ts
src/schedule/infra/out/persistence/mapper/category.mapper.ts
src/schedule/infra/out/persistence/schedule-persistence.module.ts
src/schedule/schedule.module.ts

- 카테고리 애그리거트 추가, 카테고리 생성 기능 추가
- 모듈 의존성 배열 리팩토링

✨ Feat: 카테고리 생성 기능 추가

---

src/auth/infra/in/http/adapter/auth.controller.ts
src/common/config/database/typeorm-config.service.ts
src/schedule/application/command/schedule.command-handler.ts
src/schedule/application/query/category.query-handler.ts
src/schedule/infra/in/http/adapter/category.controller.ts
src/schedule/infra/in/http/dto/category.res.ts
src/schedule/infra/in/http/mapper/category.mapper.ts

- 카테고리 api 엔드포인트 추가
- oauth 요청 시 리다이렉션되는 클라이언트 주소 변경
- typeORM 컬럼 및 테이블 네이밍 설정 추가

✨ Feat: 카테고리 생성 Api 엔드포인트 추가

---

package.json
src/auth/infra/in/strategy/jwt-access.strategy.ts
src/common/config/database/typeorm-config.service.ts
src/common/guard/jwt-access-auth.guard.ts
src/schedule/application/command/schedule.command.ts
src/schedule/application/service/category.service.ts
src/schedule/application/service/schedule.service.ts
src/schedule/domain/model/schedule.ts
src/schedule/domain/port/out/handle-category.port.ts
src/schedule/domain/port/out/handle-schedule.port.ts
src/schedule/infra/in/http/adapter/category.controller.ts
src/schedule/infra/in/http/adapter/schedule.controller.ts
src/schedule/infra/in/http/dto/schedule.req.ts
src/schedule/infra/in/http/mapper/schedule.mapper.ts
src/schedule/infra/out/persistence/adapter/category-repository.adapter.ts
src/schedule/infra/out/persistence/adapter/schedule-repository.adapter.ts
src/schedule/infra/out/persistence/mapper/schedule.mapper.ts
src/schedule/schedule.module.ts
src/user/application/service/user.service.ts
src/user/domain/port/out/handle-user.port.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts

- 일정 수정 비즈니스 로직 호출 및 트랜잭션 추가
- userId 입력 시 검증 가드 추가
- 리포지토리 업데이트 메소드 파라미터 리팩토링
- package.json 스크립트 수정

✨ Feat: 일정 추가 비즈니스 로직 호출 및 트랜잭션 추가

---

src/common/util/date-time.util.ts
src/schedule/application/query/calendar.query-handler.ts
src/schedule/application/query/calendar.query.ts
src/schedule/application/service/calendar.service.ts
src/schedule/application/service/schedule.service.ts
src/schedule/domain/model/calendar.ts
src/schedule/domain/model/schedule-read-model.ts
src/schedule/domain/port/in/get-calendar.usecase.ts
src/schedule/domain/port/in/get-schedule.usecase.ts
src/schedule/domain/port/out/load-schedule.port.ts
src/schedule/infra/in/http/adapter/calendar.controller.ts
src/schedule/infra/in/http/dto/calendar.req.ts
src/schedule/infra/in/http/dto/calendar.res.ts
src/schedule/infra/in/http/dto/schedule.req.ts
src/schedule/infra/in/http/dto/schedule.res.ts
src/schedule/infra/in/http/mapper/schedule.mapper.ts
src/schedule/infra/out/persistence/adapter/schedule-repository.adapter.ts
src/schedule/infra/out/persistence/mapper/schedule.mapper.ts
src/schedule/schedule.module.ts

- 월별 캘린더 조회 기능
- 월별 캘린더 초기화
- date에서 월 시작 및 종료 유틸 메소드 추가

✨ Feat: 메인 월별 캘린더 초기화 및 조회

---

src/common/util/date-time.util.ts
src/main.ts
src/microservice-app.module.ts
src/notification/notification.module.ts
src/schedule/application/query/calendar.query-handler.ts
src/schedule/application/service/calendar.service.ts
src/schedule/infra/out/persistence/adapter/category-repository.adapter.ts
src/schedule/schedule.module.ts
src/user/domain/model/user.ts
src/user/domain/port/out/handle-user.port.ts
src/user/domain/port/out/load-user.port.ts
src/user/infra/in/http/adapter/user.controller.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts
src/user/infra/out/persistence/entity/follow.entity.ts
src/user/infra/out/persistence/user-persistence.module.ts

- 일정 조회 조건 타임존 오류 수정
- 팔로우 엔티티, 리포지토리 추가

🐛 Fix: 일정 조회 조건 타임존 오류 수정

---

src/notification/application/command/notification.command-handler.ts
src/notification/application/command/notification.command.ts
src/notification/application/service/notification.service.ts
src/notification/domain/port/in/send-notification.usecase.ts
src/notification/infra/in/message/adapter/notification.controller.ts
src/user/domain/port/out/handle-user.port.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts

- 알림 모듈에서 필요한 기본 구조 추가(import된 파일이 없어 오류발생)로 오류 수정

✨Feat: 알림 모듈 기본구조 추가

---

src/schedule/application/service/schedule.service.ts
src/schedule/infra/in/http/adapter/category.controller.ts
src/schedule/infra/in/http/adapter/schedule.controller.ts
src/schedule/infra/out/persistence/adapter/category-repository.adapter.ts
src/schedule/infra/out/persistence/adapter/schedule-repository.adapter.ts
src/user/application/command/user.command-handler.ts
src/user/application/command/user.command.ts
src/user/application/query/user.query-handler.ts
src/user/application/query/user.query.ts
src/user/application/service/user.service.ts
src/user/domain/model/user-read-model.ts
src/user/domain/port/in/follow.usecase.ts
src/user/domain/port/in/get-user.usecase.ts
src/user/domain/port/out/load-user.port.ts
src/user/infra/in/http/adapter/user.controller.ts
src/user/infra/in/http/dto/user.res.ts
src/user/infra/in/http/mapper/user.mapper.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts
src/user/infra/out/persistence/mapper/user.mapper.ts
src/user/user.module.ts

- 사용자 팔로우 기능 추가
- 컨트롤러 가드 누락 수정
- 카테고리 정렬 조회

✨Feat: 사용자 팔로우 기능 추가

---

src/schedule/application/query/schedule.query.ts
src/schedule/application/service/schedule.service.ts
src/schedule/domain/port/in/get-schedule.usecase.ts
src/schedule/domain/port/out/load-schedule.port.ts
src/schedule/infra/in/http/adapter/schedule.controller.ts
src/schedule/infra/in/http/dto/schedule.res.ts
src/schedule/infra/in/http/mapper/schedule.mapper.ts
src/schedule/infra/out/persistence/adapter/schedule-repository.adapter.ts

- 일정 조회 시 카테고리 id 누락 수정 (일정, 카테고리 연결테이블 추가 중 누락)

🐛 Fix: 일정 조회 시 카테고리id 누락

---

src/schedule/infra/in/http/adapter/schedule.controller.ts

🐛 Fix: jwt 가드 누락

---

src/schedule/domain/model/schedule-read-model.ts
src/user/application/query/user.query-handler.ts
src/user/application/query/user.query.ts
src/user/application/service/user.service.ts
src/user/domain/model/user-read-model.ts
src/user/domain/port/in/get-user.usecase.ts
src/user/domain/port/out/load-user.port.ts
src/user/infra/in/http/adapter/user.controller.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts
src/user/user.module.ts

✨ Feat: 팔로워 팔로잉 조회

---

src/user/application/service/user.service.ts
src/user/domain/model/user-read-model.ts
src/user/domain/port/out/handle-user.port.ts
src/user/domain/port/out/load-user.port.ts
src/user/infra/in/http/adapter/user.controller.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts

- 팔로우 승인 거절 예외처리
- 컨트롤러 문법 오류 수정

🐛 Fix: 팔로우 승인 거절 예외처리

---

src/user/application/query/user.query.ts
src/user/infra/in/http/adapter/user.controller.ts
src/user/user.module.ts

🐛 Fix: 동적 경로 순서 오류 및 충돌 해결

---

src/auth/application/service/auth.service.ts
src/auth/application/service/oauth.service.ts
src/user/application/query/user.query-handler.ts
src/user/application/query/user.query.ts
src/user/application/service/user.service.ts
src/user/domain/model/user-read-model.ts
src/user/domain/port/in/get-user.usecase.ts
src/user/domain/port/out/load-user.port.ts
src/user/infra/in/http/adapter/user.controller.ts
src/user/infra/in/http/dto/user.res.ts
src/user/infra/in/http/mapper/user.mapper.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts
src/user/infra/out/persistence/mapper/user.mapper.ts
src/user/user.module.ts

- 사용자 프로필 조회 시 팔로워 수 추가
- 사용자 조회 도메인 모델, 리드 모델 및 리포지토리 조회 메소드 분리
- 오타 수정

✨ Feat: 사용자 프로필 조회 시 팔로워 수 추가

---

src/user/application/query/user.query.ts
src/user/application/service/user.service.ts
src/user/domain/model/user-read-model.ts
src/user/domain/port/out/load-user.port.ts
src/user/infra/in/http/dto/user.res.ts
src/user/infra/in/http/mapper/user.mapper.ts
src/user/infra/out/persistence/adapter/user-repository.adapter.ts
src/user/infra/out/persistence/entity/follow.entity.ts
src/user/infra/out/persistence/test-user-initialize.service.ts
src/user/infra/out/persistence/user-persistence.module.ts

- 팔로우 상태 값 isApproved 제거 및 FollowRelationStatus 인터페이스추가
- 사용자 조회 시 FollowStatus 함께 리턴
- 사용자 조회 요청 주체와 타겟이 같을 때 조건 분기

♻️ Refactor: 사용자 프로필 조회 시 팔로우 관계 상태 추가

---

tsconfig.build.json

🐛 Fix: 테스트 폴더 빌드 제외

---

src/notification/domain/model/notification-type.ts
src/user/application/command/user.command-handler.ts
src/user/application/command/user.command.ts
src/user/application/service/user.service.ts
src/user/domain/port/in/follow.usecase.ts
src/user/infra/in/http/adapter/user.controller.ts
src/user/user.module.ts

✨ Feat: 팔로우 요청 승인 전 요청 취소
